### ISSUE TITLE
`new Request` bad type

### ISSUE THREAD

**Issue by probablykasper** [cloudflare/workers-types#317] opened 2022-11-07 22:51 UTC
When creating a request, it seems like the native `Request` type is used. So when I run `new Request(url, options)`, the `options` type accepts properties that Cloudflare Workers doesn't support: `mode`, `credentials`, `cache` and `integrity` (maybe more?)

**Comment by eugene1g** [comment] 2022-11-22 14:01
This is hit&miss, but in some cases, it worked for me when to add `/// <reference types="@cloudflare/workers-types" />` as the very first line in the TypeScipt file, to help it reference CF types vs `lib.dom`.

**Comment by penalosa** [comment] 2022-11-22 17:12
It seems like you might be trying to use `workers-types` in combination with `libdom`? That's generally not a path we recommend (see the README on npm for the recommended setup). However, with the just-released `workers-types@4`, you're able to import the types, which may help:
```ts
import type { Request as WorkersRequest } from "@cloudflare/workers-types"
```

**Comment by eugene1g** [comment] 2022-11-22 17:43
It's probably fine to close this, but the problem is caused by two nuances so I'll leave further notes here -
1. IDEs often include TypeScript's `lib.dom.d.ts` for all `.ts` files even if `tsconfig.json` has a narrow list of libs like `"lib": ["ES2020"]`
2. When the code references global objects like `new Request(url)`, the IDE will use the definition of `Request` from `lib.dom.d.ts` that ships with TypeScript, which has incorrect types (for example, the `cf` parameter is missing). 
3. Importing the custom type for Request from `@cloudflare/workers-types` will not help because the code uses the actual `new Request()` runtime object which cannot be (reasonably) changed in type via TS type hints. 
That's why the workaround is to tell TypeScript to use `@cloudflare/workers-types` for that file as I showed in the example above. In theory, doing this override in tsconfig.json with the `types` directive works the same (as is explained in the README), but that didn't do the trick for me several times.

**Comment by probablykasper** [comment] 2022-11-22 18:06
@penalosa I don't have `libdom` anywhere. My `tsconfig.json` is the same as what's suggested in the README, except I have `"module": "esnext"` instead of `"CommonJS"`.

@eugene1g Adding `> /// <reference types="@cloudflare/workers-types" />` to the start of the file doesn't seem to fix it unfortunately. Also, the `cf` parameter isn't missing for me - I have both `cf` and `mode`, etc.

**Comment by penalosa** [comment] 2022-11-23 18:40
@probablykasper If you're seeing `cf` _and_ `mode`, that's definitely unexpected behaviour. It's most likely that libdom or libwebworker is being included somewhere (perhaps by a framework you're using?), but could you clarify the version of the types you're using, and whether `@cloudflare/workers-types@4` fixes the issue?

**Comment by probablykasper** [comment] 2022-11-23 19:02
I'm using v4 now, but it was also an issue on v3

**Comment by penalosa** [comment] 2022-11-23 23:14
Would you be able to set up a reproduction repository?

**Comment by probablykasper** [comment] 2022-11-24 05:24
It seems to be due to a `tsconfig.json` file in a parent directory

**Closed** 2022-11-24 07:35 UTC
